### ISSUE TITLE
4.2.3.2 Feature overlap validation

### ISSUE THREAD

**Issue by tenm** [CDS-VRN/CDS-BIJ12#27]

**Comment by stefanvanwouw** [comment]
We gaan beginnen met integratie testen van dit feature (buiten de unit tests) zodra we test data hebben die door de andere validaties heen komt.

**Comment by stefanvanwouw** [comment]
We moeten denk nog een check inbouwen die bij beforeJob en afterJob kijkt of de job wel een Import of Validate job is. Anders doen we een overlapvalidatie bij een removejob of tagjob of transformjob.

**Comment by stefanvanwouw** [comment]
Dit feature werkt zoals verwacht, behalve op het volgende punt: In de afterJob bestaat er geen mogelijkheid om de job te laten falen, op het moment dat er overlap is geconstateerd in afterJob zijn de features al naar de bronschema (PostgreSQL) database geschreven.

Hoe kunnen we dit aanpassen zodat het wel werkt, @erikorbons ? Een run time exception gooien werkt niet, dan blijft de job executor hangen in een rollback (soort deadlock ofzo, dit gebeurt ook als er een null pointer exception in de code zit).
