### ISSUE TITLE
Check dat de H2 database files worden verwijderd op unix.

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#33]
Windows houdt de files in-use waardoor ze niet programmatisch kunnen worden verwijderd. Als het goed is heeft unix (productie) hier geen last van.

**Comment by stefanvanwouw** [comment]
De docker containers op acceptatie laten geen sporen na in /tmp/ (het pad waar de H2 database files worden aangemaakt). Ik zie echter ook niet dat ze worden aangemaakt.

**Comment by erikorbons** [comment]
Dat is ook mijn conclusie in de testomgeving. Wel kan het even duren voordat de bestanden daadwerkelijk verwijderd worden, de corresponderende ETL-job is dan al voorbij. Ik vermoed dat H2 dit asynchroon scheduled in de achtergrond of (maar dat zou me verbazen) dat dit wordt overgelaten aan een finalizer.

Linksom of rechtsom verdwijnen de H2-databases waardoor dit probleem mi niet speelt. Denk dat deze gesloten kan worden.
