### ISSUE TITLE
DoelX attributen multipliciteit

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#35]
doelBeheer, doelInrichting, doelVerwerving kunnen ook een lijst van ; separated waarden bevatten. Dit is nog niet geimplementeerd.

**Comment by reinoldp** [comment]
Beste Reinold,

Het CDS voorziet in principe niet in validatie van complexe structuren, maar er zijn beperkte voorzieningen voor het valideren van lijsten die bestaan uit niet-complexe waarden (getallen, strings, etc.). Hiervoor bestaat een forEach aanroep in de validator.

Voor een voorbeeld kun je kijken naar de validator voor siteDesignation bij Protected Sites (getSiteDesignationValidator). Hier zit ook nog een vreemde workaround in omdat hier complexe waarden worden gecombineerd in een string door een ":" als separator te gebruiken, dit lijkt me voor VRN niet nodig.

Rond 3 uur / half 4 verwacht ik weer telefonisch beschikbaar te zijn.

-- 

Met vriendelijke groet,

Erik Orbons
