### ISSUE TITLE
UC11-Vaststellen Metadata

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#41]
Moeten we ook nog iets doen met de metadata tabel bij het vaststellen ?

**Comment by reinoldp** [comment]
Metadata moet instelbaar zijn voor de vastgestelde dataset. (wordt ontsloten in PGR). Hopelijk voorzit het table 'metadata' daarin. Moet uitgezocht worden of we hier ook eenvoudig de metadata van een vastgestelde dataset kunnen bewerken.

**Comment by stefanvanwouw** [comment]
Afwachten reactie klant wat betreft WFS filtering. Of we uberhaupt metadata per tag nodig hebben of metadata per thema.

**Comment by stefanvanwouw** [comment]
@Rosanvw en @reinoldp , hoe staat het met deze feature? Gaan we die wel of niet moeten implementeren, anders gooi ik hem op wontfix.
