### ISSUE TITLE
UC11-Vaststellen User interface integratie

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#42]
UI gedeelte:
Er dient een mogelijkheid te zijn om een vaststel (tag) job voor een bepaald THEMA (gebiedbeheer_landelijk, gebiedinrichting_landelijk, gebiedverwerving_landelijk) te starten via de user interface. 
Er dient een extra tabje in de UI te komen "Vaststellen" waaronder de thema's staan die vaststelbaar zijn (het tabje is niet zichtbaar als er geen vaststelbare thema's bestaan). Per vaststelbaar thema is er een input veld met submit knop. In het input veld kan een gebruiker een label invoeren waarmee het vastgestelde thema kan worden geïdentificeerd.

Controller gedeelte:
Een thema mag alleen vastgesteld worden door gebruikers met bepaalde credentials (spring security), en alleen als het thema vaststelbaar is (dit kun je checken in de VrnThemeConfig instantie bijbehorend de domeinklasse, zie DatasetConfig en VrnThemeConfig).

Het ingevoerde tag-label dient uniek te zijn. Check of het al voorkomt in de vrn.gebied(beheer/inrichting/verwerving)_landelijk_tagged tabel. En kijk ook of het voorkomt in de manager.etljob tabel.

De controller dient een TagJob aan te maken met tag="label" en table="tabelnaam van thema, bijv gebiedbeheer_landelijk".

**Comment by erikorbons** [comment]
testen of unieke tag ID bij vaststellen. Check de job_table en de tagged_table

**Comment by stefanvanwouw** [comment]
Omschrijving geupdate, er wordt neit op dataset niveau vastgesteld, maar op thema niveau (dus meerdere datasets in een klap).

**Comment by annesongithub** [comment]
De rest-URL beveiliging zal geimplementeerd worden met Spring security
