### ISSUE TITLE
Codelijst waarden whitespace gevoelig

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#49]
Als je in de aangeleverde GML een white space character te veel hebt aan het begin of einde van de waarde van een codelist element (bijvoorbeeld <beheerPakket>), dan geeft hij een fout bij het valideren.

Is dit gewenst @reinoldp ?

**Comment by reinoldp** [comment]
Ja dit is gewenst.
