### ISSUE TITLE
Gebruik JavaConfig bij VRN thema's

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/CDS-BIJ12#51]
Momenteel maakt het VRN-thema gebruik van een combinatie van JavaConfig (nl.ipo.cds.etl.theme.vrn.config.DatasetConfig), waarbij ook een XML application context wordt geïnclude voor de post-validatie.

Het is mi verwarrend om deze twee manieren van configureren te combineren. Bij het gebruik van JavaConfig was issue #46 door eclipse en door de continuous integration gesignaleerd, nu was de ontbrekende dependency pas zichtbaar na deployen in de testomgeving.

Voorstel: de beans voor de postvalidatie configureren met JavaConfig:

```
@Bean
public IBulkValidator vrnBulkValidator () {
	return new BulkValidator ();
}

@Bean
public IGeometryStore vrnGeometryStore () {
	return new H2GeometryStore ();
}
```

**Comment by stefanvanwouw** [comment]
In principe zijn er veel meer plekken waar een combinatie van Java en XML config wordt gebruikt. Het is echter wel duidelijker om het bij onze code zoveel mogelijk met Bean annotaties te doen. We kunnen dit dus oppakken als lage prioriteit.

**Comment by stefanvanwouw** [comment]
Issue #77 fixt dit.
