### ISSUE TITLE
Parsen gml zonder doelInrichting - NullPointer Exception

### ISSUE THREAD

**Issue by martijnsenden** [CDS-VRN/CDS-BIJ12#67]
Testomgeving; 2.0-vrn-0.1

Als je een gml valideert waar het veld doelInrichting wordt weggelaten (Bronhouder: Drenthe, Thema: ProvinciaalGebiedInrichting), dan valideert dit niet, en krijg je als foutmelding:

Fout bij parsen Features. Oorzaak: NullPointerException:

Dat zou ik niet verwachten. Dit veld is alleen verplicht voor Provincies die aanleveren aan het CDS, niet voor Landelijke organisaties die leveren aan het CDS. Gezien het gekozen thema, zou ik dus geen validatiefout verwachten. Als ik deze gml voor het thema LandelijkGebiedInrichting toevoeg en valideer, krijg ik wel een validatiefout en geen nullpointer exception parsefout. Ik krijg hier netjes de melding:

Het attribuut "doelInrichting" ontbreekt, feature: id2b852594-5944-424e-9f09-302108acfa16, inspireIdLocalId: NL.IMNa.6B96F21F-27ED-4483-8824-9DD085F8E286

Dat lijkt me prima. Maar voor de thema's waar dit veld niet verplicht is, moet de parser het ontbreken van dit veld ook goed en zonder nullpointer-excepties verwerken, lijkt me....?

Deze foutmeldingen treden op dezelfde manier ook op bij doelBeheer en doelVerwerving.

**Comment by stefanvanwouw** [comment]
Hoi Martijn. Zou je de link naar de gml/xsd combinatie file die je gebruikt kunnen toevoegen, dan kan ik met dit issue aan de slag.

**Comment by martijnsenden** [comment]
http://ftp.geodan.nl/vrn/data/test/attributen/test-alle-attributen-(in-drenthe)-040-geen-doelinrichting.gml;http://ftp.geodan.nl/vrn/data/test/attributen/imna_vrn_all.xsd;GebiedAll

**Comment by stefanvanwouw** [comment]
@Rosanw zal even duidelijkheid scheppen waar doelX nu wel e niet verplicht is volgens BIJ12.

**Comment by Rosanvw** [comment]
Met BIJ12 is het volgende afgesproken:
Het attribuut doelBeheer/doelInrichting /doelVerwerving (deze vallen alle drie onder het domein doelRealisatie) mag laag zijn bij datasets afkomstig van bronhouders, maar moet gevuld zijn bij datasets die door de provincies worden ge-upload.

**Comment by stefanvanwouw** [comment]
Ofwel: Bij LandelijkGebiedX is het attribuut verplicht, bij ProvinciaalGebiedX niet.
