### ISSUE TITLE
Weglaten beheerpakket attribuut valideert niet

### ISSUE THREAD

**Issue by martijnsenden** [CDS-VRN/CDS-BIJ12#68]
Testomgeving; 2.0-vrn-0.1

Als je beheer pakket niet opneemt in de gml en vervolgens valideert (thema ProvinciaalGebiedBeheer, bronhouder: Drenthe; testbestand: test-alle-attributen-(in-drenthe)-017-geen-beheerpakket.gml), krijg je een foutmelding van de validator:

Het attribuut "beheerpakket" ontbreekt, feature: id2b852594-5944-424e-9f09-302108acfa16, inspireIdLocalId: NL.IMNa.6B96F21F-27ED-4483-8824-9DD085F8E286

De parser slikt het ontbreken van het attribuut kennelijk wel (in xsd staat dat het ook nul keer mag voorkomen).

Het gaat om een optioneel attribuut. Je zou verwachten dat het gewoon valideert als dit element wordt weggelaten.

**Comment by annesongithub** [comment]
Martijn checkt bij Nick. In de code wordt het inderdaad in de AbstractGebiedBeheerValidator als NotNull gevalideerd.

**Comment by stefanvanwouw** [comment]
Als ik het me goed herinner staat dit in het FO als verplicht en in de GLP's als optioneel. Nick gaf toen aan dat de GLP's leidend zijn. Blijkbaar heb ik dit naderhand niet aangepast in de code.

**Comment by martijnsenden** [comment]
Goed, Anne-Ruth pakt dit op als optioneel attribuut. In de drie GLP's wordt dit één keer vermeld, en dan alleen als optioneel attribuut Bij Beheer in de 'GLP RVO aan gemeenschappelijke landelijke voorziening'.
