### ISSUE TITLE
UC11-Vaststellen backend afhandeling

### ISSUE THREAD

**Issue by annesongithub** [CDS-VRN/CDS-BIJ12#7]
Functionaliteit voor vaststellen van een dataset

**Comment by stefanvanwouw** [comment]
Al getest, maar nog niet helemaal inclusief integratie frontend. Dit moet nog.

**Comment by stefanvanwouw** [comment]
Wijzigingen: er dient een heel thema, niet per specifieke dataset vastgesteld te worden.

**Comment by stefanvanwouw** [comment]
Alleen nog even integratietesten als de frontend code ook klaar is.

**Comment by stefanvanwouw** [comment]
Wijzigingen van issue #24 doorvoeren en testen.
