### ISSUE TITLE
Validatie op acceptatie geeft onvolledige foutmeldingen

### ISSUE THREAD

**Issue by martijnsenden** [CDS-VRN/CDS-BIJ12#70]
Acceptatie is 2.2.-vrn-0.2
Testomgeving; 2.0-vrn-0.1

Als ik onderstaande gml/xsd valideer, dan krijg ik  op acceptatie een in mijn ogen onvolledige foutmelding. Ik krijg alleen te zien dat er 'iets' is foutgegaan, maar niet 'wat'.
Op test krijg ik een veel specifiekere melding. Dat lijkt me wenselijk. Anders heb je als gebruiker geen idee wat er mis is met je gml.

De gml en xsd string die ik heb gebruikt:
http://ftp.geodan.nl/vrn/data/test/attributen/test-alle-attributen-(in-drenthe)-001-begintijd-dubbel.gml;http://ftp.geodan.nl/vrn/data/test/attributen/imna_vrn_all.xsd;GebiedAll

Dit is maar een voorbeeld. Het treed niet alleen bij deze gml op, maar meer in het algemeen.

**Comment by stefanvanwouw** [comment]
Zou je wederom de versie nummers erbij willen zetten? (huidige versie op acceptatie is 2.2.-vrn-0.2). bvd.

**Comment by stefanvanwouw** [comment]
Dit lijkt niet meer voor te komen in versie 2.2-vrn-0.3 op acc. Het zou wel kunnen dat dit nog voorkomt door de nachtelijke import. Daar even op wachten.

**Comment by stefanvanwouw** [comment]
Na de nachtelijke import/validatie zie ik gewoon duidelijke foutmeldingen op acc versie 2.2-vrn-0.3.1
