### ISSUE TITLE
Als multisurfaceproperty mist in XSD, is er een onvolledige attributemapping.

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#76]
Dit komt voor op 2.2.-vrn-0.3.1 acceptatie.

**Comment by reinoldp** [comment]
Dit is geen bug. Als er geen multisurfaceproperty is, moet handmatig in het mapping scherm een lege waarde worden toegekend. We gaan uit van het 90% scenario. Dit is gebaseerd op de data template file van Nick. Hierin komt wel een multisurfaceproperty voor. Uitzonderingen moeten handmatig worden nabewerkt. Dit is zo afgestemd met Bij12
