### ISSUE TITLE
Overlap validatie enorm traag op grote datasets

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#77]

**Comment by stefanvanwouw** [comment]
@erikorbons weet jij een manier om meerdere validatie messages te genereren in 1 validatiemethod in AbstractVrnValidator ? Zie https://github.com/CDS-VRN/CDS-BIJ12/blob/77-overlap-validation-performance/vrn-themes/src/main/java/nl/ipo/cds/etl/theme/vrn/validation/AbstractVrnValidator.java#L247 , regel 247 kan vaker getriggered worden per feature (een feature kan een geometrie bevatten dat met meerdere geometrieen van andere features overlapt).  De huidige implementatie genereert maar maximaal 1 validatie message per feature. Daaraan kan je dus niet zien met welke geometrieen precies deze feature geometrie intersect.

**Comment by erikorbons** [comment]
Via het "Context" object kun je een instantie van de ValidationReporter opvragen. Deze heeft een methode waarmee je expliciet meldingen kunt loggen vanuit je loopje.

**Comment by stefanvanwouw** [comment]
We gaan nu ook een alternatief uitproberen waarbij de h2 database wordt gebruikt om de data op disk op te slaan ipv memory.
