### ISSUE TITLE
VoortgangsRapportageNatuur WFS returns wrong content-type

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-BIJ12#81]
Instead of application/xml;charset=UTF-8, it returns application/vnd.ogc.se_xml which not recognised by modern browsers.

The other WFSs like ProtectedSites, do return application/xml as content-type.

version: 2.2-vrn-0.4.1 on ACC

**Comment by stefanvanwouw** [comment]
Dit lijkt eerder een feature te zijn. De content types zijn valid volgens OGC. Ik zou zeggen dat we dit zo laten als het met QGIS e.d. geen problemen geeft.

**Comment by reinoldp** [comment]
Mee eens. Geen probleem in QGIS e.d.

**Comment by reinoldp** [comment]
Gaat kennelijk goed in [FireFox](https://geonet.esri.com/thread/85095), dus het is praktischer om daar de wfs in te testen.
