### ISSUE TITLE
Mag superuser vaststellen?

### ISSUE THREAD

**Issue by reinoldp** [CDS-VRN/CDS-BIJ12#86]
Om een thema te mogen vaststellen heeft een gebruiker met super-user rechten nu additionele rol VASTSTELLER nodig voor elk thema. Dit is niet consistent met andere functionaliteit waarbij een superuser wel rechten heeft.

**Comment by stefanvanwouw** [comment]
Ik maak hier een fix voor. Een superuser moet alles kunnen.

**Comment by stefanvanwouw** [comment]
Er bleek nog meer niet goed te staan qua checks in vaststellen. Dit ook gefixt:

- Het vaststeltabje was alleen zichtbaar voor superusers, niet users die wel vast mogen stellen maar geen superuser zijn.
- Na op "vaststellen"gedrutk te hebben kreeg je in alle gevallen een fout dat je geen rechten had (superuser of niet). Dit kwam omdat er een BronhouderThema object met een Thema object werd vergeleken ipv Thema met Thema.
