### ISSUE TITLE
Probleem bij meerdere RAADPLEGER rechten

### ISSUE THREAD

**Issue by reinoldp** [CDS-VRN/CDS-BIJ12#87]
Bij het filteren op bronhouder geometrie wordt nu de eerste bronhouder-thema combinatie genomen waarbij het thema overeenkomt met het featureType. Dit gaat mis wanneer er meerdere van dit type rechten zijn. Wanneer b.v. op de acceptatie omgeving met gebruiker drenthe het thema ProvinciaalGebiedBeheer wordt opgevraagd, ontstaat de volgende error:
```xml
 <ows:Exception exceptionCode="NoApplicableCode">
      <ows:ExceptionText>Bronhouder Natuurmonumenten heeft geen geldige geometrie.</ows:ExceptionText>
    </ows:Exception>
```
Voorstel is om alle geldige bronhouder geometrieen te combineren.  Eventueel alternatief is om voor het uitlezen van de provinciale datasets een speciale gebruiker te maken die alleen autorisatie heeft voor een specifieke provincie. In dat laatste geval hoeft er geen code gewijzigd te worden.

Voorbeeld [WFS request voor acc](https://cds-vrn-acc.geodan.nl/VoortgangsRapportageNatuur/services/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&typeName=imna:ProvinciaalGebiedBeheer "WFS request")

**Comment by stefanvanwouw** [comment]
De error die je aanhaalt is niet het gevolg van het meerdere bronhouders hebben per gebruiker. De landelijke bronhouders als natuurmonumenten en staatsbosbeheer hebben simpelweg geen geometrie en daarom krijg je die error. Deze bronhouders zouden dus nooit geraadpleegd kunnen worden via de WFS (?) , behalve indirect doordat hun features in een geometrie van een provincie als drenthe liggen.

Los daarvan staat nog steeds het probleem als je bijvoorbeeld een gebruiker hebt met meerdere provincie bronhouders (Overijssel én Drenthe bijvoorbeeld). Dan pakt de filter slechts de eerste provincie die in de database voorkomt en voegt die toe aan de filter.

**Comment by reinoldp** [comment]
Besproken in hangout: geomtrieen van alle bronhouders waar voor het gevraagde thema RAADPLEGER rechten zijn worden gecombineerd.
