### ISSUE TITLE
Dubbelingen in Thema dropdown in datasets tab

### ISSUE THREAD

**Issue by martijnsenden** [CDS-VRN/CDS-BIJ12#90]
Versie: acc 2.2-vrn-0.4.4

Vraag:
In het gebruikersoverzicht heb ik admin en bij12 rechten gegeven om vast te stellen:
https://cds-vrn-acc.geodan.nl/admin/ba/gebruikersbeheer/autorisatie/gebruikers

Ik heb hier gekozen voor bronhouder Drenthe (omdat ik nou eenmaal een bronhouder moet kiezen in de interface). De code doet echter alleen iets met het thema en de gebruiker, begrijp ik van Stefan.

Probleem van deze methode is dat ik nu, wanneer ik inlog als drenthe, een dubbeling krijg in de dropdownlijst met thema's in het dataset overzicht:
https://cds-vrn-acc.geodan.nl/admin/ba/datasetconfig/14

Dit lijkt me niet wenselijk. Is dit een bug, of moet ik op een andere manier aangeven dat een gebruiker vaststeller is? Als ik het wel goed gedaan heb, dan is het denk ik nodig om het dropdownlijstje te ontdubbelen.

**Comment by erikorbons** [comment]
Dat lijkt mij een bug, ik pak 'm op.

**Comment by erikorbons** [comment]
Treedt op wanneer er meerdere gebruikers permissies hebben op een thema: er mist een filter op gebruiker bij het vaststellen van de lijst van beschikbare thema's.
