### ISSUE TITLE
Provincie onterecht geauthorisateerd voor toevoegen provinciaalgebiedbeheer, -inrichitng en -verwerving.

### ISSUE THREAD

**Issue by martijnsenden** [CDS-VRN/CDS-BIJ12#92]
Als je een provincie rechten geeft als databeheerder op LandelijkGebiedBeheer, -Inrichting en -Verwerving en als raadpleger op ProvinciaalGebiedBeheer, -Inrichting en -Verwerving, dan krijgt deze provincie toch de mogelijkheid om nieuwe datasets toe te voegen voor bronhouder drenthe, thema ProvinciaalGebiedBeheer. Als raadpleger op dit thema, lijkt me dat niet de bedoeling.

Van Stefan begrijp ik dat de rechten niet goed gecheckt worden op verschillende plekken. Graag aanpassen zodat dit voldoet aan de volgende tabel. Hierbij kun je LTBO en RVO.nl als één rij zien, ze hebben dezelfde rechten.

Rollen vs Functies:
![image](https://cloud.githubusercontent.com/assets/214528/6506205/8a254b26-c349-11e4-9906-2b2f2c79c50e.png)

**Comment by martijnsenden** [comment]
getest op test 2.2-vrn-0.4.1

**Comment by erikorbons** [comment]
Zou gerelateerd kunnen zijn aan #90, zou ik even na moeten kijken. Wat verstaan jullie onder "verschillende plekken"?

**Comment by martijnsenden** [comment]
Dat kan Stefan je beter vertellen, maar ik denk in het etl-ocerzicht en in het dataset overzicht.

**Comment by stefanvanwouw** [comment]
@erikorbons Als er een DATABEHEERDER rol aan een gebruiker is toegekend (op een willekeurig thema), kan die gebruiker ook datasets toevoegen aan themas waar hij slechts RAADPLEGER is. Ik ga dit even fixen, niet zo ingewikkeld.

**Comment by martijnsenden** [comment]
Ik zou ook even moeten testen of de wfs-beveiliging goed checkt. Een provincie zou die niet moeten mogen ophalen. Heb ik nog niet getest, meen ik. Ga ik even doen.

**Comment by erikorbons** [comment]
@stefanvanwouw: je doet er verstandig aan om in dat geval verder te bouwen op CDS-VRN/InSpider#65, aangezien een deel van het probleem hier volgens mij al in is opgelost.

**Comment by erikorbons** [comment]
Nu ook gemerged in de master.

**Comment by stefanvanwouw** [comment]
Lijkt inderdaad opgelost @erikorbons. Het enige wat je nu nog ziet is dat je bij de gebruiker "drenthe" in het ETL overzicht lege ProvinciaalX thema's in de dropdown ziet, terwijl daar nooit datasets aan toegevoegd gaan worden. Gebruiker drenthe heeft echter wel RAADPLEGER rechten op bronhouder Drenthe nodig om spullen uit de WFS te halen die er onder bijvoorbeeld bronhouder natuurmonumenten zijn ingezet.
